/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as MyUsageRouteImport } from './routes/my-usage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as BudgetsIndexRouteImport } from './routes/budgets/index'
import { Route as UsersUserEmailRouteImport } from './routes/users/$userEmail'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const MyUsageRoute = MyUsageRouteImport.update({
  id: '/my-usage',
  path: '/my-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIndexRoute = BudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserEmailRoute = UsersUserEmailRouteImport.update({
  id: '/users/$userEmail',
  path: '/users/$userEmail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-usage': typeof MyUsageRoute
  '/overview': typeof OverviewRoute
  '/users/$userEmail': typeof UsersUserEmailRoute
  '/budgets': typeof BudgetsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-usage': typeof MyUsageRoute
  '/overview': typeof OverviewRoute
  '/users/$userEmail': typeof UsersUserEmailRoute
  '/budgets': typeof BudgetsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-usage': typeof MyUsageRoute
  '/overview': typeof OverviewRoute
  '/users/$userEmail': typeof UsersUserEmailRoute
  '/budgets/': typeof BudgetsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-usage'
    | '/overview'
    | '/users/$userEmail'
    | '/budgets'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-usage'
    | '/overview'
    | '/users/$userEmail'
    | '/budgets'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/my-usage'
    | '/overview'
    | '/users/$userEmail'
    | '/budgets/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyUsageRoute: typeof MyUsageRoute
  OverviewRoute: typeof OverviewRoute
  UsersUserEmailRoute: typeof UsersUserEmailRoute
  BudgetsIndexRoute: typeof BudgetsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-usage': {
      id: '/my-usage'
      path: '/my-usage'
      fullPath: '/my-usage'
      preLoaderRoute: typeof MyUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/': {
      id: '/budgets/'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userEmail': {
      id: '/users/$userEmail'
      path: '/users/$userEmail'
      fullPath: '/users/$userEmail'
      preLoaderRoute: typeof UsersUserEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyUsageRoute: MyUsageRoute,
  OverviewRoute: OverviewRoute,
  UsersUserEmailRoute: UsersUserEmailRoute,
  BudgetsIndexRoute: BudgetsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
